FROM openjdk:8-jdk-alpine as builder

COPY ./out/artifacts/fibcalc_jar/fibcalc.jar /usr/app/

FROM arm64v8/openjdk:20 as arm64
COPY --from=builder /usr/app/fibcalc.jar /usr/app/fibcalc.jar
WORKDIR /usr/app
ENTRYPOINT ["java", "-jar", "fibcalc.jar"]

FROM amd64/openjdk:20 as amd64
COPY --from=builder /usr/app/fibcalc.jar /usr/app/fibcalc.jar
WORKDIR /usr/app
ENTRYPOINT ["java", "-jar", "fibcalc.jar"]

LABEL org.opencontainers.image.source="https://github.com/PanAdam15/FiboCalc"