name: Chmury_Zad1

on:
  push:
    branches: [main]
    tags: [v*]

      
jobs:
  build-push-images:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        architecture: [x64, arm64]
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3
      # This is a separate action that sets up buildx runner|
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # So now you can use Actions' own caching!
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            panadam15/zad1
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}} 
            
      # And make it available for builds
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          buildkit: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platform: 
            -linux/amd64
            -linux/arm64/v8
          cache-from: type=registry,ref=docker.io/panadam15/zad1:cache
          cache-to: type=registry,ref=docker.io/panadam15/zad1:cache,mode=max
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
